name: editorial
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  bcrypt: ^1.1.3  

  # FIREBASE - PARA AUTENTICACIÓN, BASE DE DATOS, ALMACENAMIENTO Y FIRESTORE
  firebase_core: ^4.0.0        # INICIALIZA LOS SERVICIOS DE FIREBASE
  firebase_auth: ^6.0.0        # MANEJA AUTENTICACIÓN DE USUARIOS
  firebase_database: ^12.0.0   # BASE DE DATOS EN TIEMPO REAL
  cloud_firestore: ^6.0.0      # BASE DE DATOS NO RELACIONAL FIRESTORE
  firebase_storage: 13.0.0     # ALMACENAMIENTO DE ARCHIVOS EN LA NUBE

  # SQLITE - PARA BASE DE DATOS LOCAL Y MODO OFFLINE
  drift: ^2.28.2                # PAQUETE PRINCIPAL DE DRIFT
  drift_flutter: ^0.2.7         # EXTENSIÓN DE DRIFT PARA INTEGRACIÓN CON FLUTTER
  sqlite3_flutter_libs: ^0.5.39 # BIBLIOTECAS NATIVAS DE SQLITE NECESARIAS
  sqflite_common_ffi: ^2.3.0

  # GESTIÓN DE ESTADO Y ACCESO A ARCHIVOS
  path_provider: ^2.1.2 # GESTIÓN DE ESTADO REACTIVA
  provider: ^6.1.1      # ACCESO A DIRECTORIOS DEL DISPOSITIVO
  path: ^1.8.3

  
  # MANEJO DE ARCHIVOS, COMPARTIR Y GENERACIÓN DE DOCUMENTOS
  image_picker: ^1.0.4   # SELECCIÓN DE IMÁGENES DESDE GALERÍA O CÁMARA
  file_selector: ^1.0.3  #SELECTOR DE CARPETA DE ARCHIVOS
  file_selector_windows: ^0.9.2
  screenshot: 3.0.0      # CAPTURA DE PANTALLA DEL WIDGET
  share_plus: ^11.1.0    # COMPARTIR CONTENIDO ENTRE APLICACIONES
  file_picker: ^10.3.2   # SELECCIÓN DE ARCHIVOS DESDE EL SITEMA
  pdf: ^3.10.4           # GENERACIÓN Y MANIPULACIÓN DE ARCHIVOS PDF
  csv: ^6.0.0            # LECTURA Y ESCRITURA DE ARCHIVOS CSV
  qr_flutter: ^4.1.0     # GENERA CÓDIGO QR


  # DISEÑO Y VISUALIZACIÓN DE DATOS
  cupertino_icons: ^1.0.8 # ICONOS ESTILO IOS
  fl_chart: ^1.0.0        # GRAFICAS Y VISUALIZACIONES DE DATOS
  intl: ^0.20.2           # FORMATO DE FECHAS, NÚMEROS Y LOCAZIÓN
  
  # PERMISOS Y UTILIDADES
  permission_handler: ^12.0.1 # MANEJO DE PERMISOS DEL SISTEMA
  diacritic: ^0.1.6           # ELIMINA ACENTOS Y CARACTERES ESPECIALES DE TEXTOS
  
  # AUTENTICACIÓN Y BASE DE DATOS ALTERNATIVA
  supabase_flutter: ^2.0.0    #CLIENTE PARA SUPABASE, ALTERNATIVA A FIREBASE
  msix: ^3.16.12


# DEPENDENCIAS DE DESARROLLO
dev_dependencies:
  flutter_test:
    sdk: flutter          # PRUEBAS UNITARIA Y DE WIDGETS
  flutter_lints: ^6.0.0   # REGLAS DE ESTILO Y BUENAS PRÁCTICAS  DE CÓDIGO
  drift_dev: ^2.16.0      # GENERADOR DE CÓDIGO PARA DRIFT
  build_runner: ^2.4.8    # EJECUTA LA GENERACIÓN DE CÓDIGO
# 
flutter:

  uses-material-design: true

  assets:
    - assets/ocelote.png
    - assets/siresu.png
    - assets/unach.png
    - assets/manita.png
    - assets/sinportada.png
    - assets/icono.png

